spring:
  datasource:
    url: jdbc:mysql://rm-uf6747h40s8g1841lo.mysql.rds.aliyuncs.com:3306/electric_bicycle_pro_test
    userName: jjdc_123
    password: jjdc_99bicycle
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
#      cluster-name: elasticsearch
      cluster-nodes: 172.16.20.14:9300
      repositories:
        enabled: true
  redis:
    database: 0
    host: 172.16.20.195
    port: 6379
    timeout: 30000
    password: test123

# LOGGING
logging:
    level:
       com.example: DEBUG
    config: classpath:logback/logback-dev.xml
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  config-location: classpath:mybatis/mybatis.xml
geTui:
  config: appId:qs7TAAijc78EYeZr2nbZZ3
          appKey:4tYioFVKcT7xJdgold5iT2
          masterSecret:hZcEq5a57U8pAEySOcWpR8
          host:https://api.getui.com/apiex.htm
